export const metadata = {
  title: "Contact",
  description: "description for the contact page",
};

export default function About() {
  return (
    <div className="mt-[200px]">
      <p className="font-bold text-center uppercase text-3xl">contact</p>

      <div className="w-[80%] mx-auto mt-[50px]">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vestibulum pretium euismod. Sed enim dui, vestibulum sed ipsum vitae, rhoncus congue nisi. Nulla cursus nibh ipsum, id fermentum diam mollis ut. Curabitur sodales mauris nisl, et egestas ex pretium ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed semper velit. Praesent porta aliquet mi quis varius. Donec faucibus, ligula nec congue iaculis, tellus mauris consequat ligula, et vulputate dui sem ac lorem. Suspendisse ipsum nulla, tincidunt nec molestie eu, mollis at felis.</p>
      </div>
    </div>
  );
}